### PR TITLE
eliminates the awkward Tracked abstraction

### PR DESCRIPTION
**Pull request by dherman**
See issue #14.

### CODE REVIEW

**Comment by RReverser** [comment]
I'm curious if builder pattern would work better for adding locations rather than having extra `Option<Span>` argument in each AST node enum constructor. Other than that, great work!

**Comment by RReverser** [comment]
Ah wait, it's enum so you can't really make fields optional during construction. Nevermind then.

**Comment by dherman** [comment]
I think the builder pattern will be better for choosing entirely different representations. And I wanted the AST types to be sufficiently general that they can represent:
- full source location information
- no source location information
- mixed (for example if you have tools that generate synthetic nodes that didn't come from source)

**Comment by RReverser** [comment]
@dherman Sure, I just thought that it would be nice to avoid `Option<...>` and, correspondingly, `None` when creating nodes of each single AST type and `_, `in matching patterns, but I see that it's not very trivial in this case, so good to go as-is.

**Comment by RReverser** [comment]
@dherman Ping. What's the further plan on this?

**Pull request merged**
