### PR TITLE
Update nonascii identifier characters.

### PR DESCRIPTION
**Pull request by braddunbar**
Use symbols with ID_Start and ID_Continue derived core properties for lexing identifiers.

This fixes all but one test in `ES6/identifier`. The remaining test concerns `await` being a reserved word in a module context and can be fixed in a separate patch.

https://mathiasbynens.be/notes/javascript-identifiers-es6
http://unicode.org/Public/9.0.0/ucd/DerivedCoreProperties.txt

I generated the code points with the following script and then removed the ASCII symbols.

```
#!/bin/bash

curl "http://unicode.org/Public/9.0.0/ucd/DerivedCoreProperties.txt" |
  grep '; ID_Start' |
  sed -e 's- .*--g' |
  awk -F '.' '{ if ($3) printf("(\047\\u{%s}\047,\047\\u{%s}\047),", $1, $3); else printf("\047\\u{%s}\047,", $1) }' > 'id-start.txt'

curl "http://unicode.org/Public/9.0.0/ucd/DerivedCoreProperties.txt" |
  grep '; ID_Continue' |
  sed -e 's- .*--g' |
  awk -F '.' '{ if ($3) printf("(\047\\u{%s}\047,\047\\u{%s}\047),", $1, $3); else printf("\047\\u{%s}\047,", $1) }' > 'id-continue.txt'
```

### CODE REVIEW

**Comment by RReverser** [comment]
Awesome, thanks!

Would you like to add that script somewhere to the repo?

Also, could you remove ES6/identifier from .testignore and replace with just that test that is still known to fail?

**Comment by braddunbar** [comment]
Sure thing! Swapped out the line in `.testignore` in 2be0f1990af6bbe98e0e5889be40c8decdcda496 and I'll add the script later on this evening.

Thanks for taking a look @RReverser! 😺

**Comment by RReverser** [comment]
Hmm, according to Travis, this brings ~6% slowdown to generic benchmarks. Probably we will need to improve unicode identifier parsing in future by putting outside of the fast path. https://travis-ci.org/dherman/esprit/jobs/198363466

**Comment by braddunbar** [comment]
I can see that some of these could be compressed to ranges. I'll see if I can write a script to fix that.

**Comment by RReverser** [comment]
@braddunbar Theoretically this shouldn't matter for Rust in optimized mode and it should figure out such things on its own.

**Comment by RReverser** [comment]
Huh, maybe it does (which looks like optimizer bug) https://godbolt.org/g/8bB2et

**Comment by RReverser** [comment]
Although indeed things like `...('\u{01C4}','\u{0293}'),'\u{0294}',('\u{0295}','\u{02AF}')...` look like they could be a single range. Is there any reason they're not?

**Comment by RReverser** [comment]
@braddunbar Any luck with merging ranges? Would love to merge this PR.

**Comment by braddunbar** [comment]
Yep, yep! Wrote up an awk script to merge them last night. Pushed in 0a74b7df45332263c83f17cc08c7d032ba64f9b0.

```
#!/usr/bin/env awk -f

function range(from, to) {
  if (from == to) {
    return "'\\u{" from "}'"
  } else {
    return "('\\u{" from "}','\\u{" to "}')"
  }
}

BEGIN {
  FS="."
  type = "; " ENVIRON["TYPE"] " #"
}

$0 ~ type {
  sub(/ .*$/, "")

  # Skip ascii characters.
  if (("0x" $1) + 0 <= 128) next

  if (!to || ("0x" $1) + 0 != ("0x" to) + 1) {
    if (to) printf range(from, to) ","
    from = $1
  }
  to = $3 ? $3 : $1
}

END { printf range(from, to) }
```

**Comment by braddunbar** [comment]
*I wasn't sure where to add the script to the repo. Just let me know where if you'd like it added!*

**Comment by RReverser** [comment]
The difference is now around 3% which seems negligible enough.

As for the script - gave it another though, and probably it's something we should do in Rust-land so that this would work cross-platform. Thanks for the update though.

**Comment by braddunbar** [comment]
Thanks @RReverser! I have some ideas on how to speed this up that I'll send later. Perhaps I'll take a stab at a Rust script for extracting them as well. 👍

**Comment by RReverser** [comment]
@braddunbar Turns out there are already crates for that, delegated this task to `ucd` so that we wouldn't need to maintain it independently. Thanks again for your contribution though :)

**Comment by braddunbar** [comment]
Excellent! Thanks for the update @RReverser! 😺

**Pull request merged**
