### PR TITLE
read_decimal_digits_into -> read_decimal_digits

### PR DESCRIPTION
**Pull request by braddunbar**
Since read_decimal_digits will allocate the string for us, we can just use it to do so!

### CODE REVIEW

**Comment by RReverser** [comment]
This seems to be the only place where `read_decimal_digits` will be used? Perhaps easier to just drop it in favor of more generic `read_decimal_digits_into`? cc @dherman

**Comment by braddunbar** [comment]
Looks like `read_decimal_digits` is [used](https://github.com/braddunbar/esprit/blob/b6e6ab954557c1d12785b3a01b37c7cff1c291a0/crates/joker/src/lexer.rs#L378) [twice](https://github.com/braddunbar/esprit/blob/b6e6ab954557c1d12785b3a01b37c7cff1c291a0/crates/joker/src/lexer.rs#L391) in `read_number`, but `read_decimal_digits_into` is only used once after this change.

I inlined it in bd85862522c7841769f833d2c138ce9a357fc487, but I'm happy to reverse it if you prefer. 🙃

**Comment by RReverser** [comment]
Ah makes sense.

**Comment by RReverser** [comment]
This is a pretty small non-breaking change, so I'll merge it right away. Looks good, thanks!

**Comment by braddunbar** [comment]
Thanks! 🙌🏻

**Pull request merged**
